spring.application.name=Hackathon
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/SchemeNavigator}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true

gemini.api.key=${GOOGLE_API_KEY}

jdbc:postgresql://dpg-d9ouiglbedkc73dog960-a/jansahayak_db
jansahayak_db_user:NAmOCZyK4uZ6pLWMY0pK6MMCEflKtXX9@